import 'package:develop_app_hoangnm/core/data/remote/entity/autogenerated.dart';
import 'package:develop_app_hoangnm/core/data/remote/services/autogenerated_service.dart';

abstract class AutogeneratedRepository {
  Future<List<MenuItems>?> getDateApiAutogenerated();

}

class AutogeneratedRepositoryImp extends AutogeneratedRepository {
  final AutogeneratedService _autogeneratedService =  AutogeneratedService();


  static AutogeneratedRepositoryImp? _instance;

  AutogeneratedRepositoryImp._();

  void destroyInstance() {
    _instance = null;
  }

  factory AutogeneratedRepositoryImp() {
    return _instance ??= AutogeneratedRepositoryImp._();
  }


  @override
  Future<List<MenuItems>?> getDateApiAutogenerated() async {
    Autogenerated? response = await _autogeneratedService.getAutogenerated();
    return response?.menuItems;
  }
}
