import 'package:develop_app_hoangnm/core/constants/api_end_point.dart';
import 'package:develop_app_hoangnm/core/data/remote/entity/autogenerated.dart';

import 'base_service.dart';

class AutogeneratedService extends BaseService {
  Future<Autogenerated?> getAutogenerated() async {
    mockAPIHelpers.mockGET_200(
      url: ApiEndPointConstants.autogenerated,
      jsonResponse: Autogenerated.responseDummy(),
    );
    return get(
      ApiEndPointConstants.autogenerated,
      mapper: (json) => Autogenerated.fromJson(json as Map<String, dynamic>),
    );
  }
}
