class Autogenerated {
  final List<MenuItems>? menuItems;

  Autogenerated({this.menuItems});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    List<MenuItems> list = [];
    for (Map<String, dynamic> obj in json["menu-items"]) {
      list.add(MenuItems.fromJson(obj));
    }
    return Autogenerated(menuItems: list);
  }

  @override
  String toString() {
    return "[Autogenerated: ${menuItems.toString()}]";
  }

  static dynamic responseDummy() {
    return {
      "menu-items": [
        {
          "id": "94298",
          "name": "3 Chicken Wings",
          "position": 1,
          "description": "Tender, Spicy and Juicy. Original or Peri-Crusted",
          "images": "",
        },
        {
          "id": "94301",
          "name": "Chicken Livers and Portuguese Roll",
          "position": 2,
          "description": "Chicken Livers Topped with PERi-PERi Sauce, Served with A Roll To Soak Up The Sauce",
          "images": "",
        },
        {
          "id": "94304",
          "name": "Spicy Mixed Olives (V)",
          "position": 3,
          "description": "Co-Starring Garlic, Pepper and Chili",
          "images": "",
        },
        {
          "id": "94307",
          "name": "Hummus with PERI-PERI Drizzle (V)",
          "position": 4,
          "description": "Pour Smoky PERi-PERi Oil Over Creamy Hummus and Dig in with Strips Of Warm Pita",
          "images": "",
        },
        {
          "id": "94310",
          "name": "Red Pepper Dip (V)",
          "position": 5,
          "description": "Dive Into Temping Roasted Red Pepper and Chili Spice Dip with Warm Pita Strips",
          "images": [],
        },
        {
          "id": "94313",
          "name": "Appeteaser Platter",
          "position": 6,
          "description": "Choose any Three Appeteasers",
          "images": "",
        },
        {
          "id": "94316",
          "name": "All Together Now (V)",
          "position": 7,
          "description": "Spicy Mixed Olives, Red Pepper Dip, Hummus with PERi-PERi Drizzle and Warm Pita Strips",
          "images": "",
        }
      ]
    };
  }
}

class MenuItems {
  int? id;
  String? name;
  int? position;
  String? description;
  String? images;

  MenuItems(
      {this.id,
        this.name,
        this.position,
        this.description,
        this.images,
      });


  factory MenuItems.fromJson(Map<String, dynamic> json) =>
      MenuItems(
        id: int.parse(json["id"].toString()),
        name: json["name"] as String?,
        position: int.parse(json["position"].toString()),
        description: json["description"] as String? ?? "",
      );

  @override
  String toString() {
    // TODO: implement toString
    return "id $id name $name,position: $position, description: $description, images: $images";
  }
}

