import 'package:develop_app_hoangnm/conponent/base_view/base_view_model.dart';
import 'package:develop_app_hoangnm/core/data/remote/api/api_exception.dart';
import 'package:develop_app_hoangnm/core/data/remote/entity/autogenerated.dart';
import 'package:develop_app_hoangnm/core/data/repositories/autogenerated_repo.dart';
import 'package:develop_app_hoangnm/core/utils/log_utils.dart';
import 'package:flutter/cupertino.dart';

class HomeViewModel extends BaseViewModel {

  final AutogeneratedRepository _friendRepository = AutogeneratedRepositoryImp();

  late List<MenuItems> _list = [];
  List<MenuItems> get list => _list;

  @override
  void onInitViewModel(BuildContext context) {
    super.onInitViewModel(context);
    _listItemMenu();
  }

  Future<void> _listItemMenu() async {
    await _friendRepository.getDateApiAutogenerated().then(
          (results) async {
        _list = results ?? [];
        LogUtils.d("[_list] => $results]");
        updateCurrentUI();
      },
    ).onError<ApiException>((error, stackTrace) {
        LogUtils.d("[$runtimeType] API ERROR $error");
      },
    );
  }
}